### PR TITLE
feat: add flow emulator and dev-wallet

### PR DESCRIPTION
**Pull request by fubz**
Here is my first attempt at adding the flow emulator and dev-wallet.  Is there an alternative to manually deploying the Profile contract after starting the emulator?  https://docs.onflow.org/flow-cli/project-contracts/ seems to imply that by adding the Profile contract to the deployment section of the flow.json should deploy the contract upon starting the emulator; however, that is currently not occurring.

### CODE REVIEW

**Comment by muttoni** [comment]
I love it! Thanks for the contribution :) I'll play with this over the weekend. Just some thoughts right off the bat:

-  Any chance we can make local vs testnet a flaggable option? Or local by default, and testnet as a flag? Or some way of easily switching between the two? Maybe even as simple as having 2 different config files that people can switch by renaming them, and specifying that in the README.md
- I like the fact that people can try this and get up and running on testnet without any flow cli dependencies. In your opinion, what should we start with? Maybe it's worth keeping testnet as default to try it out quickly, and then add instructions in the readme that for development it's recommended to switch to local development, and to do that one must install the flow cli, switch the config files and follow the deployment instructions. 

What do you think?

**Comment by fubz** [comment]
I agree this needs flags for testnet vs emulator which could be accomplished with some environment variable magic. 

As for the projects default mode I think testnet would be the better default so the deployment to vercel is ready to go out of the box.  I did like the fact that when the vercel bot deployed the preview of the PR, the app still worked as long as my emulator was still running locally.

**Comment by fubz** [comment]
@muttoni when you get a chance take a look at my new commit, I think you will be very pleased.

I started by adding testnet vs emulator environment variables.  I took the Next.js approach and made dev mode use the emulator variables while production mode (or npm start) will allow the user to run the project on testnet with no additional commands.  This aligns with the official Next.js documented approach: https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables

Next up, I refactored the users authentication and transaction logic into their own React contexts.  This makes the logic more production ready and able to be used in multiple components.  Especially the transaction logic where additional blockchain transactions can reuse the same logic and components.

Finally I did a minor refactor to extract out the Profile and integrate the existing components with the Contexts.  This made the code easier to read since the files are not as long anymore.  I also added prettier because I can't live without it :)

I also figured out the non deprecated commands for starting the emulator and deploying contracts to the emulator based upon the flow.json configuration.

I hope you like the changes and they don't deviate too far from your vision!

**Review by muttoni — APPROVED** [review]
Amazing stuff @fubz ! Merged <3 

Works great here! Will only add a little disclaimer to log out when switching between testnet and emulator as that can trigger an error when the address doesnt exist in the emulator. Other than that, it's perfect! :)

**Comment by muttoni** [comment]
Closes #1

**Pull request merged**
